// GENERATED by scripts/gen-katex-fonts — KaTeX font-face rules with inline data-URI fonts.
// The stylesheet's relative font paths cannot resolve inside a srcdoc iframe, and a
// sandboxed iframe (opaque origin) would need CORS headers for cross-origin font
// requests — so each woff2 is bundled as a data URI via Vite's ?inline query.

import font_KaTeX_AMS_Regular_woff2 from 'katex/dist/fonts/KaTeX_AMS-Regular.woff2?inline';
import font_KaTeX_Caligraphic_Bold_woff2 from 'katex/dist/fonts/KaTeX_Caligraphic-Bold.woff2?inline';
import font_KaTeX_Caligraphic_Regular_woff2 from 'katex/dist/fonts/KaTeX_Caligraphic-Regular.woff2?inline';
import font_KaTeX_Fraktur_Bold_woff2 from 'katex/dist/fonts/KaTeX_Fraktur-Bold.woff2?inline';
import font_KaTeX_Fraktur_Regular_woff2 from 'katex/dist/fonts/KaTeX_Fraktur-Regular.woff2?inline';
import font_KaTeX_Main_Bold_woff2 from 'katex/dist/fonts/KaTeX_Main-Bold.woff2?inline';
import font_KaTeX_Main_BoldItalic_woff2 from 'katex/dist/fonts/KaTeX_Main-BoldItalic.woff2?inline';
import font_KaTeX_Main_Italic_woff2 from 'katex/dist/fonts/KaTeX_Main-Italic.woff2?inline';
import font_KaTeX_Main_Regular_woff2 from 'katex/dist/fonts/KaTeX_Main-Regular.woff2?inline';
import font_KaTeX_Math_BoldItalic_woff2 from 'katex/dist/fonts/KaTeX_Math-BoldItalic.woff2?inline';
import font_KaTeX_Math_Italic_woff2 from 'katex/dist/fonts/KaTeX_Math-Italic.woff2?inline';
import font_KaTeX_SansSerif_Bold_woff2 from 'katex/dist/fonts/KaTeX_SansSerif-Bold.woff2?inline';
import font_KaTeX_SansSerif_Italic_woff2 from 'katex/dist/fonts/KaTeX_SansSerif-Italic.woff2?inline';
import font_KaTeX_SansSerif_Regular_woff2 from 'katex/dist/fonts/KaTeX_SansSerif-Regular.woff2?inline';
import font_KaTeX_Script_Regular_woff2 from 'katex/dist/fonts/KaTeX_Script-Regular.woff2?inline';
import font_KaTeX_Size1_Regular_woff2 from 'katex/dist/fonts/KaTeX_Size1-Regular.woff2?inline';
import font_KaTeX_Size2_Regular_woff2 from 'katex/dist/fonts/KaTeX_Size2-Regular.woff2?inline';
import font_KaTeX_Size3_Regular_woff2 from 'katex/dist/fonts/KaTeX_Size3-Regular.woff2?inline';
import font_KaTeX_Size4_Regular_woff2 from 'katex/dist/fonts/KaTeX_Size4-Regular.woff2?inline';
import font_KaTeX_Typewriter_Regular_woff2 from 'katex/dist/fonts/KaTeX_Typewriter-Regular.woff2?inline';

export const KATEX_FONT_FACES = `
@font-face{font-family:KaTeX_AMS;font-style:normal;font-weight:400;font-display:swap;src:url(${font_KaTeX_AMS_Regular_woff2}) format('woff2')}
@font-face{font-family:KaTeX_Caligraphic;font-style:normal;font-weight:700;font-display:swap;src:url(${font_KaTeX_Caligraphic_Bold_woff2}) format('woff2')}
@font-face{font-family:KaTeX_Caligraphic;font-style:normal;font-weight:400;font-display:swap;src:url(${font_KaTeX_Caligraphic_Regular_woff2}) format('woff2')}
@font-face{font-family:KaTeX_Fraktur;font-style:normal;font-weight:700;font-display:swap;src:url(${font_KaTeX_Fraktur_Bold_woff2}) format('woff2')}
@font-face{font-family:KaTeX_Fraktur;font-style:normal;font-weight:400;font-display:swap;src:url(${font_KaTeX_Fraktur_Regular_woff2}) format('woff2')}
@font-face{font-family:KaTeX_Main;font-style:normal;font-weight:700;font-display:swap;src:url(${font_KaTeX_Main_Bold_woff2}) format('woff2')}
@font-face{font-family:KaTeX_Main;font-style:italic;font-weight:700;font-display:swap;src:url(${font_KaTeX_Main_BoldItalic_woff2}) format('woff2')}
@font-face{font-family:KaTeX_Main;font-style:italic;font-weight:400;font-display:swap;src:url(${font_KaTeX_Main_Italic_woff2}) format('woff2')}
@font-face{font-family:KaTeX_Main;font-style:normal;font-weight:400;font-display:swap;src:url(${font_KaTeX_Main_Regular_woff2}) format('woff2')}
@font-face{font-family:KaTeX_Math;font-style:italic;font-weight:700;font-display:swap;src:url(${font_KaTeX_Math_BoldItalic_woff2}) format('woff2')}
@font-face{font-family:KaTeX_Math;font-style:italic;font-weight:400;font-display:swap;src:url(${font_KaTeX_Math_Italic_woff2}) format('woff2')}
@font-face{font-family:"KaTeX_SansSerif";font-style:normal;font-weight:700;font-display:swap;src:url(${font_KaTeX_SansSerif_Bold_woff2}) format('woff2')}
@font-face{font-family:"KaTeX_SansSerif";font-style:italic;font-weight:400;font-display:swap;src:url(${font_KaTeX_SansSerif_Italic_woff2}) format('woff2')}
@font-face{font-family:"KaTeX_SansSerif";font-style:normal;font-weight:400;font-display:swap;src:url(${font_KaTeX_SansSerif_Regular_woff2}) format('woff2')}
@font-face{font-family:KaTeX_Script;font-style:normal;font-weight:400;font-display:swap;src:url(${font_KaTeX_Script_Regular_woff2}) format('woff2')}
@font-face{font-family:KaTeX_Size1;font-style:normal;font-weight:400;font-display:swap;src:url(${font_KaTeX_Size1_Regular_woff2}) format('woff2')}
@font-face{font-family:KaTeX_Size2;font-style:normal;font-weight:400;font-display:swap;src:url(${font_KaTeX_Size2_Regular_woff2}) format('woff2')}
@font-face{font-family:KaTeX_Size3;font-style:normal;font-weight:400;font-display:swap;src:url(${font_KaTeX_Size3_Regular_woff2}) format('woff2')}
@font-face{font-family:KaTeX_Size4;font-style:normal;font-weight:400;font-display:swap;src:url(${font_KaTeX_Size4_Regular_woff2}) format('woff2')}
@font-face{font-family:KaTeX_Typewriter;font-style:normal;font-weight:400;font-display:swap;src:url(${font_KaTeX_Typewriter_Regular_woff2}) format('woff2')}
`;
